ccv/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from .views import indexView, PostListView


urlpatterns = [
    path('', indexView, name='index'),
    path('posts/', PostListView.as_view(), name='postListView'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

main/models.py
from django.db import models

class PostModel(models.Model):
    postId = models.IntegerField()
    postTypeId = models.IntegerField()
    parentId = models.IntegerField()
    creationDate = models.DateTimeField()
    score = models.IntegerField()
    viewCount = models.IntegerField()
    body = models.TextField()
    ownerUserId = models.IntegerField()
    lastEditorUserId = models.IntegerField()
    lastEditDate = models.DateTimeField()
    lastActivityDate = models.DateTimeField()
    commentCount = models.IntegerField()

main/forms.py
from django import forms

class submitXmlForm(forms.Form):
    xmlfile = forms.FileField()

main/views.py
import datetime
import xml.etree.ElementTree as ET
from django.shortcuts import render
from django.db.models import Q
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework import generics
from .serializers import PostSerializer
from .models import PostModel
from .forms import submitXmlForm


def indexView(request):
    if request.method == 'POST':
        form = submitXmlForm(request.POST, request.FILES)
        if form.is_valid():
            xml_parser(request.FILES['xmlfile'])
        return render(request, 'done.html')
    form = submitXmlForm()
    return render(request, 'index.html', { 'form':form })

def xml_parser(filename):
    tree = ET.parse(filename)
    root = tree.getroot()

    for child in root:
        data = child.attrib
        postObj = PostModel()
        try:
            postObj.postId = data['Id']
        except KeyError as e:
            postObj.postId = 0

        try:
            postObj.postTypeId = data['PostTypeId']
        except KeyError as e:
            postObj.postTypeId = 0

        try:
            postObj.parentId = data['ParentId']
        except KeyError as e:
            postObj.parentId = 0
        try:
            postObj.creationDate = data['CreationDate']
        except KeyError as e:
            postObj.creationDate = datetime.datetime.now()

        try:
            postObj.score = data['Score']
        except KeyError as e:
            postObj.score = 0

        try:
            postObj.body = data['Body']
        except KeyError as e:
            postObj.body = 'no body'

        try:
            postObj.viewCount = data['ViewCount']
        except KeyError as e:
            postObj.viewCount = 0

        try:
            postObj.ownerUserId = data['OwnerUserId']
        except KeyError as e:
            postObj.ownerUserId = 0

        try:
            postObj.lastEditorUserId = data['LastEditorUserId']
        except KeyError as e:
            postObj.lastEditorUserId = 0

        try:
            postObj.lastEditDate = data['LastEditDate']
        except KeyError as e:
            postObj.lastEditDate = datetime.datetime.now()

        try:
            postObj.lastActivityDate = data['lastActivityDate']
        except KeyError as e:
            postObj.lastActivityDate = datetime.datetime.now()

        try:
            postObj.commentCount = data['CommentCount']
        except KeyError as e:
            postObj.commentCount = 0

        postObj.save()


class PostListView(generics.ListAPIView):
    serializer_class = PostSerializer

    def get_queryset(self):

        queryset = PostModel.objects.all()
        orderby = self.request.query_params.get('orderby', None)

        search = self.request.query_params.get('search', None)

        if orderby is not None:
            if orderby == 'score':
                queryset =  queryset.order_by('score')
            if orderby == 'view_count':
                queryset = queryset.order_by('viewCount')

        if search is not None:
            queryset = queryset.filter(body__contains=search)

        return queryset

main/templates/done.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Uploaded</title>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css" integrity="sha384-oAOxQR6DkCoMliIh8yFnu25d7Eq/PHS21PClpwjOTeU2jRSq11vu66rf90/cZr47" crossorigin="anonymous">
  </head>
  <body>
    Data has been uploaded
  </body>
</html>

main/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CCV</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q=" crossorigin="anonymous" />
  </head>
  <body>
    <div class="ui container" style="margin-top:50px">
      <div class="ui very padded center aligned segment">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="ui labeled input">
              <div class="ui label">
                XML File
              </div>
              <input type="file" name="xmlfile" required id="id_xmlfile">
            </div> <br> <br>
            <input class="ui blue button" type="submit" name="submit" value="Submit">
        </form>
      </div>
    </div>
  </body>
</html>